source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'

# Use postgresql as the database for Active Record
gem 'pg'

gem 'active_model_serializers'

# Spring speeds up development by keeping your application running in the background. 
# Read more: https://github.com/rails/spring
gem 'spring', group: :development

